name: Run Tests
on:
  push:
    branches:
      - main
    pull_request:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    env: 
      TESTING: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.10'
      
      - name: Setup Python Virtual Environment
        run: python3 -m venv python3-virtrualenv
      
      - name: Install Dependencies
        run: pip install -r requirements.txt
      
      - name: Give Run Script Permissions
        run: chmod +x run_test.sh

      - name: Run Tests
        run: ./run_test.sh
